import React from "react";
import {
  Document, Page, Text, View, StyleSheet, renderToBuffer,
} from "@react-pdf/renderer";
import type { Audit } from "@revagent/db";
import type { Objection, JtbdPatterns, BuyerPhrase } from "@revagent/shared";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: "Helvetica", color: "#111" },
  h1: { fontSize: 22, marginBottom: 4, fontWeight: 700 },
  subtitle: { fontSize: 11, color: "#666", marginBottom: 24 },
  section: { marginBottom: 18 },
  h2: { fontSize: 14, fontWeight: 700, marginBottom: 6, color: "#1f3a5f" },
  item: { marginBottom: 4 },
  badge: { fontSize: 9, color: "#888" },
  quote: { fontStyle: "italic", color: "#333" },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#888" },
});

interface DigestProps {
  audits: Audit[];
}

function Digest({ audits }: DigestProps) {
  const wonAudits = audits.filter((a) => a.outcome === "won");
  const lostAudits = audits.filter((a) => a.outcome === "lost");

  const wonPatterns = wonAudits.flatMap((a) =>
    ((a.jtbdPatterns as JtbdPatterns | null)?.pattern_match ?? []).map((p: string) => ({ pattern: p, dealId: a.dealId })),
  ).slice(0, 3);

  const lostPatterns = lostAudits.flatMap((a) =>
    ((a.jtbdPatterns as JtbdPatterns | null)?.pattern_match ?? []).map((p: string) => ({ pattern: p, dealId: a.dealId })),
  ).slice(0, 2);

  const objections = audits.flatMap((a) =>
    ((a.objections as Objection[] | null) ?? []).map((o) => ({ ...o, dealId: a.dealId, outcome: a.outcome })),
  )
  .sort((a, b) => severityRank(b.severity) - severityRank(a.severity))
  .slice(0, 5);

  const phrases = audits.flatMap((a) =>
    ((a.buyerLanguage as BuyerPhrase[] | null) ?? []),
  ).slice(0, 10);

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.h1}>RevAgent — Win-Loss Digest</Text>
        <Text style={styles.subtitle}>
          Pattern analysis across {audits.length} deal{audits.length === 1 ? "" : "s"} · generated {new Date().toLocaleDateString()}
        </Text>

        <View style={styles.section}>
          <Text style={styles.h2}>3 patterns in won deals</Text>
          {wonPatterns.length === 0 && <Text style={styles.item}>— no won-deal patterns yet —</Text>}
          {wonPatterns.map((p, i) => (
            <Text key={i} style={styles.item}>
              {i + 1}. {p.pattern} <Text style={styles.badge}>(deal {p.dealId})</Text>
            </Text>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.h2}>2 patterns in lost deals</Text>
          {lostPatterns.length === 0 && <Text style={styles.item}>— no lost-deal patterns yet —</Text>}
          {lostPatterns.map((p, i) => (
            <Text key={i} style={styles.item}>
              {i + 1}. {p.pattern} <Text style={styles.badge}>(deal {p.dealId})</Text>
            </Text>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.h2}>5 objections to pre-empt</Text>
          {objections.map((o, i) => (
            <Text key={i} style={styles.item}>
              {i + 1}. [{o.severity.toUpperCase()}] {o.objection}{" "}
              <Text style={styles.badge}>(deal {o.dealId} · {o.outcome})</Text>
            </Text>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.h2}>10 verbatim buyer phrases (ready for copy)</Text>
          {phrases.map((p, i) => (
            <View key={i} style={styles.item}>
              <Text style={styles.quote}>"{p.phrase}"</Text>
              <Text style={styles.badge}> → {p.use_case} · {p.context}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by RevAgent · 4-stage Featherless pipeline · MIT-licensed at revagent.ai
        </Text>
      </Page>
    </Document>
  );
}

function severityRank(s: Objection["severity"]): number {
  return s === "high" ? 3 : s === "medium" ? 2 : 1;
}

export async function generateDigestPdf(args: DigestProps): Promise<Buffer> {
  const buffer = await renderToBuffer(<Digest {...args} />);
  return buffer as unknown as Buffer;
}
